targets:
  $default:
    builders:
      getx_gen:
        generate_for:
          - test/*

builders:
  getx_gen:
    import: "package:getx_gen/src/builder.dart"
    builder_factories: ["getxPageBuilder"]
    build_extensions: { ".dart": ["getx_gen.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]